# Generated by Django 5.1.4 on 2024-12-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amt', models.IntegerField()),
                ('transtot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_at', models.DateTimeField(auto_now_add=True)),
                ('amt', models.IntegerField()),
                ('trans_name', models.FloatField()),
            ],
        ),
    ]
