# Generated by Django 5.1.4 on 2024-12-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='budget_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='transtot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_name',
            field=models.CharField(max_length=100),
        ),
    ]
