# Generated by Django 5.1.4 on 2024-12-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_transaction_id_transaction_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='budget_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.budget'),
        ),
    ]
