# Generated by Django 5.1.4 on 2024-12-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_transaction_budget_alter_transaction_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.budget'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100)),
                ('goal_amount', models.IntegerField()),
                ('saved_amount', models.IntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to='tracker.budget')),
            ],
        ),
    ]
